title: Konstantinos Chondralis
description: Embedded Software Engineer & Microcontroller Enthusiast - Portfolio showcasing embedded systems projects and technical expertise
author: Konstantinos Chondralis
email: khondralis@gmail.com
theme: jekyll-theme-minimal

# Site settings
url: "https://kostantinoss.github.io"
baseurl: ""

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# SEO
seo:
  type: Person
  links:
    - https://github.com/kostantinoss
    - https://www.linkedin.com/in/konstantinos-chondralis
