title: Konstantinos Chondralis
description: Personal portfolio website
author: Konstantinos Chondralis
email: khondralis@gmail.com
theme: jekyll-theme-minimal

# Site settings
url: "https://kostantinoss.github.io"
baseurl: ""

# Build settings
markdown: kramdown
